export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const SUBMIT_APPLICATION_START = "SUBMIT_APPLICATION_START"
export const SUBMIT_APPLICATION_SUCCESS = "SUBMIT_APPLICATION_SUCCES"
export const SUBMIT_APPLICATION_FAIL = "SUBMIT_APPLICATION_FAIL"